name: waha
description: A mobile app for the students of the Athénée de Waha

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.1.3
  font_awesome_flutter: ^8.8.1
  fluttertoast: ^7.0.2
  http: 0.12.2
  awesome_dialog: ^1.1.3

  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_dynamic_links: ^0.5.3
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.7

  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0
  uuid: ^2.0.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  pedantic: ^1.8.0
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_roundable.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/loading_01.gif
     - assets/elementsGrid.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
